In [23]:
a={
    "Student_Id" :[1,2,3,4,5,6,7,8,9,10],
    "Student_Name" :["Ajay","Rohan","Sohan","Raju","Kartikey","Arpit","Ashish","Mohit","Anshul","Abhay"],
    "Roll_No" :[21,22,23,24,25,26,27,28,29,30],
    "Section" :["A","A","B","B","C","D","E","D","E","C"],
    "Batch":["A1","A1","A2","A2","A3","A1","A2","A4","A4","A3"],
    "Domain" :["AWS","PYTHON DJANGO","AWS","DATA SCIENCE","DATA ENGINEERING ","JAVA FULL STACK","DATA SCIENCE","DATA ENGINEERING","DATA ANALYST","C++"]
}

In [24]:
type(a)

dict

In [25]:
import pandas as pd

In [26]:
df= pd.DataFrame(a)
df

Student_Id Student_Name  Roll_No Section Batch             Domain
0           1         Ajay       21       A    A1                AWS
1           2        Rohan       22       A    A1      PYTHON DJANGO
2           3        Sohan       23       B    A2                AWS
3           4         Raju       24       B    A2       DATA SCIENCE
4           5     Kartikey       25       C    A3  DATA ENGINEERING 
5           6        Arpit       26       D    A1    JAVA FULL STACK
6           7       Ashish       27       E    A2       DATA SCIENCE
7           8        Mohit       28       D    A4   DATA ENGINEERING
8           9       Anshul       29       E    A4       DATA ANALYST
9          10        Abhay       30       C    A3                C++

In [27]:
df.to_csv("C:\\Users\\anski\\Desktop\\kartikey_kichara\\student_data.csv",index=False)

In [30]:
import pandas as pd

In [32]:
df2= pd.read_csv("C:\\Users\\anski\\Desktop\\kartikey_kichara\\student_data.csv")
df2

Student_Id Student_Name  Roll_No Section Batch             Domain
0           1         Ajay       21       A    A1                AWS
1           2        Rohan       22       A    A1      PYTHON DJANGO
2           3        Sohan       23       B    A2                AWS
3           4         Raju       24       B    A2       DATA SCIENCE
4           5     Kartikey       25       C    A3  DATA ENGINEERING 
5           6        Arpit       26       D    A1    JAVA FULL STACK
6           7       Ashish       27       E    A2       DATA SCIENCE
7           8        Mohit       28       D    A4   DATA ENGINEERING
8           9       Anshul       29       E    A4       DATA ANALYST
9          10        Abhay       30       C    A3                C++

In [2]:
a=[1,24,6]

In [3]:
type(a)

list

In [4]:
import numpy as np

In [5]:
a=[12,2,3]


In [6]:
arr=np.array(a)
arr

array([12,  2,  3])

In [8]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print("total rows and column",b.shape)
print("total element", b.size)
print("dimension of the array",b.ndim)

total rows and column (3, 3)
total element 9
dimension of the array 2


In [12]:
a=[]
size=int(input("enter the size"))
for i in range(size):
    val=int(input("enter the value"))
    a.append(val)
b=np.array(a)
b

enter the size 3
enter the value 45
enter the value 52
enter the value 12


array([45, 52, 12])